### ISSUE TITLE
Offer WebRTC output from OBS  via ffmpeg or custom OBS webrtc builds

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/vdo.ninja#114]

**Comment by KovalevArtem** [comment]
Do you mean this custom build?
https://github.com/CoSMoSoftware/OBS-studio-webrtc

**Comment by steveseguin** [comment]
Yes, that and via some other options I have.

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/80761077-901acf80-8b42-11ea-8b5a-4c81f874cf3d.png)
This repository looks abandoned...

**Comment by steveseguin** [comment]
this company, related to cosmos, still supports OBS webrtc output. https://www.millicast.com

That said, I have my own plugin that is command-line based that works with OBS Ninja. (or any raw video output source that can pipe into a command line)

In OBS, you can just add a secondary-output that way, and it would still let you broadcast via RTMP via the main output.

**Comment by TychoWerner** [comment]
This is now possible thru WHIP.
https://docs.vdo.ninja/advanced-settings/mixer-scene-parameters/and-whip-alpha

Recommend closing this issue.
