### ISSUE TITLE
Stream only sound

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/vdo.ninja#120]
![image](https://user-images.githubusercontent.com/36500228/81306082-bfbc6100-9087-11ea-9a9c-3e0204948d38.png)
![image](https://user-images.githubusercontent.com/36500228/81306488-36595e80-9088-11ea-8121-fb9a908ed234.png)

If the camera is not connected to the computer, it is impossible to transmit only sound! (In Google Chrome)
The solution to this problem I described [here](https://github.com/steveseguin/obsninja/issues/102#issuecomment-622120344).

**Comment by KovalevArtem** [comment]
I connected a webcam and it worked right away!
![image](https://user-images.githubusercontent.com/36500228/81306788-8e906080-9088-11ea-9c15-b37cf7bfbb4f.png)

**Comment by steveseguin** [comment]
Thank you for pointing this out.  I'll mark it as a bug.  I have like 5 cameras, and have never tried without them.
