### ISSUE TITLE
Let guests set a name viewable on group/director pages

### ISSUE THREAD

**Issue by CyBeRoni** [steveseguin/vdo.ninja#157]
Shouldn't be visible on the solo page probably, but for the director especially (and if you're sending the stream back to your guests, that too) it'd be cool if the streams they receive had some sort of label.

**Comment by steveseguin** [comment]
I did have this at one point, but removed temporary to remove smoe clutter.  I'll definitely add that back in.

Any thoughts on how it could be used beyond just labelling videos in the director's view and chat view?

**Comment by CyBeRoni** [comment]
If the label is available in an element on the page (hidden by default) you could use it for automated lower-thirds with some css in the browser source I suppose? That'd be pretty advanced usage though.

For me it'd just be to make it easier for the guests to recognise what's what on their screen. For example, I send them the stream output so they know what's going on, which is obvious enough to most but not the less technically inclined. And for me it would help to know what guest is what as I have multiple that I haven't necessarily ever seen before, that join during the stream.

**Comment by jcalado** [comment]
Could the labels be used on the director page instead of "Guest slot #x"?

**Comment by steveseguin** [comment]
Absolutely.

It will also give names to those in the text chat and allow me to offer optional on-screen text overlays.

I long had the basics in place for labels, but getting the UX figured out made it a burden for rapid development.

**Comment by CyBeRoni** [comment]
I noticed that the new director page shows the label and I can have the guest page ask for that, which is great for people like me who have guests that they don't necessarily know the name to the face for. Thanks!

**Comment by patrickbaltieri** [comment]
how can I use this function? is it working in the actual version of obs.ninja? It will be great have something like that in stream.
![d3c010eb-3e52-48ba-85a5-8540f7ba28a3](https://user-images.githubusercontent.com/75711289/101716921-1013fb00-3a7d-11eb-9062-6b83005a0ae4.png)

**Comment by steveseguin** [comment]
Overlay labels are working on BETA for viewers/guests/scenes.  Labels already exist in the director's room in production.

You need to use both &label=xxx and &showlabels for this to work on beta,

![image](https://user-images.githubusercontent.com/2575698/101717035-8bb97c00-3a6c-11eb-8b0c-82f27f1c4238.png)

example:
https://obs.ninja/beta/?view=9kF4NWC&showlabels
https://obs.ninja/beta/?label=steve&push=9kF4NWC

**Comment by patrickbaltieri** [comment]
Is it possible change the position of the label in OBS? In browser works perfectly. 
![unnamed (1)](https://user-images.githubusercontent.com/75711289/101762480-41f88200-3abc-11eb-9a27-d52ee91f96a4.png)

![unnamed](https://user-images.githubusercontent.com/75711289/101762267-f7770580-3abb-11eb-8725-40dcf34956e2.png)

**Comment by steveseguin** [comment]
Yep,

You will have several available options to you; pretty much full CSS-control over the style. I don't have any examples at this very moment, but those are coming.
