### ISSUE TITLE
On server/ws crashes, let the publisher to reclaim streamID 

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/vdo.ninja#19]
Some security issues here, but the hope is that for a short period after a stream dies the streamID will be held for the original publisher, who has a secret key.

I don't intend to have any "long" term store of streamIDs or secret keys; it's first come first-serve for now with a temporary hold only. Enough to regain a connection.

Passwords or hashes or such are possible things I could add, and I think I have an idea on how to do that, but w/ed.

**Comment by TychoWerner** [comment]
Passwords are implemented
https://docs.vdo.ninja/advanced-settings/setup-parameters/password

Suggest to close this issue.
