### ISSUE TITLE
allow for rotate/flip &flip=xxx,yyy,zz etc

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/vdo.ninja#201]
both for flip and rotate

**Comment by TychoWerner** [comment]
https://docs.vdo.ninja/advanced-settings/design-parameters/and-rotate
https://docs.vdo.ninja/advanced-settings/design-parameters/and-flip
https://docs.vdo.ninja/advanced-settings/design-parameters/mirror

Has been implemented, close this issue?
