### ISSUE TITLE
With 'No Audio' selected as the audio source it is not possible to start a feed

### ISSUE THREAD

**Issue by 0foxface** [steveseguin/vdo.ninja#234]
It's not possible to send video only - when selecting 'No Audio' in the audio source selection drop down, the green 'Press When Ready' button disappears.

Steps to replicate
Use 'Join group chat' or 'Add camera to OBS' options
Select 'No Audio' in the dropdown

**Comment by steveseguin** [comment]
Let me know if this issue still occurs.  I re-wrote the camera/audio selection interface. It's live on https://obs.ninja/ and I'll update github in the coming days after some more testing.
