### ISSUE TITLE
Video drops to 1 fps after 15 minutes.

### ISSUE THREAD

**Issue by otmanzy** [steveseguin/vdo.ninja#235]
Upon first use, the recording is smooth with just some minor pixilation but I can guarantee that it is my internet speeds. However, almost always, 15 minutes into recording, the video begins to stutter and drop to 1 fps. Furthermore, I refresh the webpage and then all of a sudden, it is smooth again.

**Comment by steveseguin** [comment]
What phone / browser / system are you using?

Also, if you are facing heavy packet loss, it could have that problem.  After 15-minutes, if it happens consistently, it could be your IP-providing throttling UDP network traffic.   Where do you live and what internet provider do you use?

I suppose I can suggest trying a different video codec; h264 or vp9.
Ensure that you are on Ethernet, and not wifi.
Lower the resolution -- perhaps 360p30 (smooth and cool)
Update graphics card drivers on both systems if possible

If using OBS, what version? Does this happen in Chrome to Chrome?

I have updated the app yesterday; it maybe might make a difference.

Sorry for the delay in response.
