### ISSUE TITLE
Feature Request: raise hand

### ISSUE THREAD

**Issue by DachsbauTV** [steveseguin/vdo.ninja#363]
We are planning a panel discussion and and I've stumbled upon a feature which would be very useful for OBS Ninja

For coordinating the talks it would be great to have a "raise hand" feature (e.g. https://support.zoom.us/hc/en-us/articles/205566129-Raising-your-hand-in-a-webinar)

**Comment by steveseguin** [comment]
Happy to add something like it --    can you give me some details on how you'd see it working?

How is this option enabled? always available?
Does that mean guests are muted by default? audio and video muted? just audio muted?
How is the director notified? Is everyone notified?

How many people are intending to be in a group webinar?

**Comment by DachsbauTV** [comment]
My idea would be:
1. Have a "activate raise hand" option (to keep the GUI as simple as possible)
2. All group members are audio muted by default and the director can unmute single participants (latch). Could be combined with the "add to Scene" So people are automatically unmuted when added to the scene
3. a raised hand will add a symbol or a frame to the persons input. Best case with a number that's counting up, so the director knows who "raised hand" first
4. How many people are participating is not really known yet. I think in our case we will have about 20-30 taking part in the discussion and the rest will just follow the live stream (which we will put out via obs)

**Comment by DachsbauTV** [comment]
Oh and in this case it would also be great if the room members can self-assign them names, that are shown under each input. So the host or director can cue people more easily

**Comment by steveseguin** [comment]
Names are a long overdue feature I've yet to add. That might come first.  

Thank you for the clarification on what you want.  I'll see if there is an easy way for me to get something basic yet functional in soon.

**Comment by steveseguin** [comment]
This adds a crude optional raised hand feature.  &hands activates it for guests.  when pressed by a guest, it shows a yellow button in the director's room for that guest's video. If the director clicks the button, it hides the yellow button. Guest can 'lower their hand", which also can remove the button.

![image](https://user-images.githubusercontent.com/2575698/101246484-ab097f80-36e1-11eb-886d-e21c28bcb7fb.png)

will improve it later; just a quick hack for now.

**Comment by DachsbauTV** [comment]
Oh totally forgot to give you feedback on this. Sorry for that.

Works great,What i would improve is to put a small raised hand icon in the preview picture to make it more visible.
I've had the issue, that the current badge dissapears in the second row of the people because of scaling and one tends to not notice before it's too latel

Would also look more slick with a smaller icon :)
Other then that it's great. Thanks again

**Comment by steveseguin** [comment]
Thank you for that feedback.

I've recently added a &beep option, which will make a noise when someone raises their hand or sends a chat message. (on beta; hopefully on production today).

I'll work on improving the raise-hand feature as I've received similar feedback a coupe times now.
