### ISSUE TITLE
Allow that Chat box to POP OUT

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/vdo.ninja#511]
I think I can do this via Inter-window Chromium chat messaing; and not load the WebRTC p2p network more

**Comment by DachsbauTV** [comment]
That'd be great. 
Also the option to have the pop-out window background transparent would be really useful then. 

(Restream.io has this feature for it's chat)

**Comment by steveseguin** [comment]
Neat request.  I might need to code it slightly differently if the chat will be used in a different browse.  Would you want it to be added to OBS or would you just want it as an iFRAME?  

If for OBS integration, I might then be better off making a view-only page designed to be used as an overlay.

**Comment by DachsbauTV** [comment]
In restream the feature is mostly used to be able to have the chat floating above another application  (e.g. you're streaming while DJing and you can have the chat as an overlay in your Serato)
Oh and of course for that you would need to option "always stay on top"

However, you are absulutely right, it could also be used as a source for OBS to have the chat on the stream.

**Comment by steveseguin** [comment]
I added a chat option to ALPHA.  it's basic, and not what everyone is looking for, but it's a start.

https://obs.ninja/alpha/

![image](https://user-images.githubusercontent.com/2575698/100501686-b71d9c00-3139-11eb-9d49-febb1b28a668.png)
