### ISSUE TITLE
Sorting webcameras by display names

### ISSUE THREAD

**Issue by Dziukens** [steveseguin/vdo.ninja#836]
It would be very useful to create a tool to sort webcameras, when display names are enabled.

**Comment by steveseguin** [comment]
Thank you for the feature request.   I assume you mean in the drop-down menu for selecting a camera source?

**Comment by Dziukens** [comment]
Drop-down menu is definitely a good way to go.

**Comment by jcalado** [comment]
Do you mean sorting people that are on screen based on their display names?

**Comment by Dziukens** [comment]
> Thank you for the feature request. I assume you mean in the drop-down menu for selecting a camera source?

I meant sorting people who connected to my room and sort those cameras in Director's Room based on Display Names.

**Comment by jcalado** [comment]
You can manually do this in the director room.
