### ISSUE TITLE
Auto highlight based on audio

### ISSUE THREAD

**Issue by fgolman** [steveseguin/vdo.ninja#842]
Not sure if I'm missing this in OBS.ninja or if it's been requested before, but I'd make a suggestion of an enhancement option to auto-highlight, in the group scene mode. Potentially even be able to designate one remote as the "moderator" above and beyond the director (to be able to override the switching).

Just a thought of a feature that could be really useful.

Fritz Golman

**Comment by jcalado** [comment]
> An 'active speaker' mixing mode has been added. It auto-hides remote guests videos when added, if those guests are not speaking actively. &activespeaker ( or &sas or &speakerview)
https://github.com/steveseguin/obsninja/wiki/v17-Release-Notes

It still hasn't been added to https://github.com/steveseguin/obsninja/wiki/Advanced-Settings but it will soon.

**Comment by steveseguin** [comment]
There is a "highlight" button the director has, where you can select a guest to be full-screen

The 'active speaker' feature in v17 will do the same mostly.  I wrote the code to 'outline' active speakers as well, but it had some technical/UX challenges, and so I put that aside for now.  Currently, active speaker just shows/hides those who are actively speaking.

I'll continue to make improvements based on feedback; thank you kindly for the request.
