### ISSUE TITLE
Audio-only Recording Working?

### ISSUE THREAD

**Issue by Cessquill** [steveseguin/vdo.ninja#869]
I've added &record=0 to the guest URL and it will still record the video (albeit in 640x480 rather than HD) - is that expected?  Have also tried negative values in Chrome & Firefox on Windows 10.

If I add &pcm, then I get the recording prompt in Firefox when I end the recording (rather than start), and I get an empty file.

Example of URL I'm trying https://obs.ninja/?room=myroomname&hash=myhash&q&record=0

Just the facility to record locally is amazing - thank you for that.  I'm now looking at capturing high quality audio for post-produced podcast interviews and voiceover commentaries.

**Comment by jcalado** [comment]
This sounds like a bug yes. I've tested it here with record=0 and it recorded video as well

**Comment by Cessquill** [comment]
Hi - just been doing some more tests on this - it appears that the record=0 records the audio locally at 64kbps.  I'm not that familiar with the webm format, and VLC & MediaInfo doesn't display anything, but Windows file properties lists the bitrate at 64kbps.  Whilst these were quick and dirty tests, it did sound quite rough; still getting my head around converting webm though, so that could be me.

I'll do some A:B tests later with full video and just audio.

**Comment by steveseguin** [comment]
Think I fixed it? 

&record=0 should result in a file contain audio-only in webm format:

`Audio: IEEE Float 48000Hz stereo 3072kbps [A: English [eng] (pcm_f32le, 48000 Hz, 2 channels, fp32, 3072 kb/s) [default]]`

seems I made a typo and broke this feature when I released v18. Thank you for reporting the issue
