### ISSUE TITLE
Recording videomix

### ISSUE THREAD

**Issue by jonnyfisher** [steveseguin/vdo.ninja#873]
Can I (as the room director)  record on the disc a videomix  with all the participants , without OBS or other apps?  Just as i can record the separate streams.

**Comment by steveseguin** [comment]
Hi Jonnyfisher,

I've added this as a feature request item already, and I have an idea on how to add it in a slick way.  For now, you'd need to do it with some hackery.

To do this currently, you'd need to open a group scene into a new Chrome tab.  `vdo.ninja/?scene&room=MYROOM `for example.

Then, you'd need to go to `https://vdo.ninja/?screenshare&record`   and select the Chrome tab (with audio).  Then press the record button that appears at the bottom.

This will record directly to disk without needing any added software.
