### ISSUE TITLE
[REQUEST] Allow translate phrases from webrtc.js

### ISSUE THREAD

**Issue by gander** [steveseguin/vdo.ninja#875]
We need to allow translating also phrases from `webrtc.js`:

```
The stream ID you are publishing to is already in use.
Please try with a different invite link or refresh to retry again.
You will now be disconnected.
```
```html
'The\x20stream\x20ID\x20you\x20are\x20publishing\x20to\x20is\x20already\x20in\x20use.\x0a\x0aPlease\x20try\x20with\x20a\x20different\x20invite\x20link\x20or\x20refresh\x20to\x20retry\x20again.\x0a\x0aYou\x20will\x20now\x20be\x20disconnected.'
```

**Comment by steveseguin** [comment]
I haven't had time to add this yet, but it's on my to-do list. Apologies

**Comment by steveseguin** [comment]
I added about ~45 new translations and moved the text contained in `webrtc.js` to an array of text in the head of `lib.js`

This should complete the request; the code is on the beta18.3 branch here: https://github.com/steveseguin/vdo.ninja/commit/e1c2ad17489447b2116169a446d6865e52a2a0cd

The line needed to be changed is here, if you want to hard code it: https://github.com/steveseguin/vdo.ninja/blob/e1c2ad17489447b2116169a446d6865e52a2a0cd/lib.js#L34
