### ISSUE TITLE
Director video not showing.

### ISSUE THREAD

**Issue by swperic** [steveseguin/vdo.ninja#879]
I am using 18.2 in chrome on windows 10. My url options are broadcast, and hide self preview.  I could not get an camera source to display on the guest side but it was showing as a active in the preview source.  Audio was passing but video is not.

**Comment by steveseguin** [comment]
Did you have any luck with this issue? 

It's possible some browsers or some mobile devices, maybe an iPhone, will have problems here.

Do you know what mobile device you are using; are you using a mobile device? I don't recall, but iOS devices may need the video be visible on screen for the video to actually be recorded.

**Comment by steveseguin** [comment]
I pushed a fix to vdo.ninja/beta --  assuming the remote camera is an iOS device, using &nopreview should now work. I show the video, but I show it off-screen now, so that seems to bypass the iOS glitch.

Closing the issue, but re-open it if you still have issues
