### ISSUE TITLE
chrome freeze tabs

### ISSUE THREAD

**Issue by DaniMinn** [steveseguin/vdo.ninja#883]
chrome freeze the tab when greenscreen is on and the page is hidden , so the streaming stops, 
it is possible change this feature?

**Comment by steveseguin** [comment]
I think I fixed this if using the Electron Capture app when streaming.  I definitely have a lot of work ahead to improve the green screen feature though; this will be one of the fixes I'll try to add.

Thank you for reporting it.

**Comment by DaniMinn** [comment]
Thank you for the answer, I tried with the Electron Capture app and it's working properly.
