### ISSUE TITLE
Can't change audio source as director on Firefox

### ISSUE THREAD

**Issue by DillFrescott** [steveseguin/vdo.ninja#884]
You can check the box to attempt to change the audio source(s), but it doesn't do anything. Upon closing and reopening the settings panel, the audio device is reset.

**Comment by steveseguin** [comment]
Thank you for pointing it out.  I just pushed a hot-fix for this into production at https://vdo.ninja  You may need to do a hard refresh for it to update.

The issue seemed to be with constraints = {audio: {deviceId: xxxxx}} no longer being compatible with Firefox.  Instead, constraints = {audio: {exact: {deviceId: xxxxx}}} is required.  meh.

**Comment by DillFrescott** [comment]
@steveseguin thank you so much!

This might be asking for a lot because I'm not sure how difficult it would be to implement, but could you add a way for people in the call to be able to change others volumes but only for them personally? So if a peer's volume is too loud or quiet they can have a personal audio adjustment.

**Comment by steveseguin** [comment]
Already added;  hover over the guest's video, and the control bar will appear. You can then lower the volume for that specific guest.
![image](https://user-images.githubusercontent.com/2575698/124371858-e65a3580-dc53-11eb-856e-e81ecb0076f7.png)

Happy to hear feedback on how I might be able to improve it though

**Comment by DillFrescott** [comment]
@steveseguin perfect!

This works on both Chrome and Firefox correct? I could test it but I'm not at the computer at the moment.

**Comment by DillFrescott** [comment]
@steveseguin Is it okay if I send you some suggestions in the future about features and ideas? I'm always looking for cool things to add to stuff like this <3

**Comment by steveseguin** [comment]
the volume should work with firefox/chrome.

I welcome feedback and suggestions;  simple requests I can often do right away. larger requests may take some months.
