### ISSUE TITLE
Server has problem now

### ISSUE THREAD

**Issue by floyd168** [steveseguin/vdo.ninja#885]
![IMG_20210709_132456](https://user-images.githubusercontent.com/83258940/125030431-b381c880-e0bd-11eb-9daf-458419a79635.jpg)
The backup site is functioning but its url is backup.obs.ninja，so app can't grap the sound

**Comment by steveseguin** [comment]
Thank you. will look into it

**Comment by steveseguin** [comment]
It should be working again

**Comment by floyd168** [comment]
> It should be working again
Thank you for your  quick response. Your project is very powerful and useful ,just save my life

**Comment by floyd168** [comment]
> It should be working again

Thank you for your quick response. Your project is very powerful and useful ,just save my life
