### ISSUE TITLE
Can't control the volume with audio only

### ISSUE THREAD

**Issue by DarKDinDoN** [steveseguin/vdo.ninja#888]
Hello,

Have this room: https://obs.ninja/?push=qwerty123456hello&videodevice=0&stereo=1&aec=0&autogain=0&denoise=0&aj&noap

![image](https://user-images.githubusercontent.com/1687854/125634561-7e7e2470-079f-4c48-a9ec-e44df4485c0d.png)

And this link for viewers: https://obs.ninja/?view=qwerty123456hello&stereo=1&audiobitrate=320&noap

![image](https://user-images.githubusercontent.com/1687854/125634685-44bde552-d2e2-4791-b59c-1614b83eab11.png)

Issue is that the viewer can't control the volume. There is no button for that in the interface.
With FF, we can right-click and select "Display controls".
With chrome, this option is no available.

**Comment by jcalado** [comment]
![image](https://user-images.githubusercontent.com/26873/131849982-50b0ecc3-772c-46f1-a886-b61d2abafa7f.png)

Can't reproduce. I have a video element control bar at the bottom of the page on latest google chrome.

**Comment by DarKDinDoN** [comment]
@jcalado Confirmed it is fixed for me as well.
Most likely a chrome bug now resolved.

**Comment by jcalado** [comment]
Great 👍
