### ISSUE TITLE
Error After 10 days working self hosted

### ISSUE THREAD

**Issue by edinsof** [steveseguin/vdo.ninja#892]
Hi
I m getting this error on (view url) when try to connect on (push url) with websocket self hosted

This problem appear 10 days after working successfully

Is it possible to activate debugging mode to investigate? 
`
VM29:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at WebSocket._0x20b587.ws.<computed> (webrtc.js?ver=214:9)`

**Comment by steveseguin** [comment]
It would appear that the data being transmitted is not JSON-compatible, so perhaps the server is giving an error.

You can diagnose this in Chrome, using the developers tool, to inspect the websocket traffic.  What message is being sent that isn't JSON?

![image](https://user-images.githubusercontent.com/2575698/129398182-64a5d48a-4b22-45ff-a132-36f9dbacbffb.png)

**Comment by edinsof** [comment]
i restarted server several times but dont works 

![wss](https://user-images.githubusercontent.com/3094013/129398523-9c0a1493-c9f6-4e5c-9d12-285ff97deee7.png)

**Comment by steveseguin** [comment]
to confirm, you're using this for the server code: https://github.com/steveseguin/websocket_server ?

**Comment by edinsof** [comment]
yes is same server code

maybe you can test my config

push - https://movil.ejeserver.com/irl/?push=h36ctKf&label=pruebas
view - https://movil.ejeserver.com/irl/?view=h36ctKf&label=pruebas

**Comment by steveseguin** [comment]
Can you go into the server.js code and modify the following:

Change 
```
client.send(message);
```
to
```
client.send(message.toString());
```
so it looks like this

```
websocketServer.on('connection', (webSocketClient) => {
    webSocketClient.on('message', (message) => {
            websocketServer.clients.forEach( client => {
                    if (webSocketClient!=client){
                        client.send(message.toString());
                    }
            });
    });
});
```

then restart the script?

**Comment by edinsof** [comment]
Code changed and server restarted

**Comment by steveseguin** [comment]
It seems to be working for me currently; let me know if it is for you as well.

**Comment by edinsof** [comment]
yes now is working
what caused the issue?

**Comment by steveseguin** [comment]
Not sure exactly, but either Chrome v92 or Nodejs updated and decided to change how they wanted to handle things it looks like. 

I added a fix to both the server code and the vdo.ninja code, so this will be fixed for others going forward also. 

Thank you for reporting the issue.
