### ISSUE TITLE
Director, Local and remote recording not working together

### ISSUE THREAD

**Issue by ConradHendricks** [steveseguin/vdo.ninja#897]
I have been testing the remote audio record function. When I only select record on the director and record remote on the guest, all is recorded fine. But when I also try to local record the guest (while I'm remote recording the guest and recording the director) there is no audio recorded for the Director, just video.

**Comment by ConradHendricks** [comment]
operator error.... no bug to report.

**Comment by steveseguin** [comment]
all cool; thank you for the consideration regardless.  I was just going to note that there might be some echo cancellation being applied, possibly causing the track to be quieter/muffled; using `&aec=0` (disabling echo cancellation) would help there.

**Comment by ConradHendricks** [comment]
Thanks. It was operator error, as fiddling with settings  caused a loss of mic connection on the director computer. Another restart of the test setup and it came good..... I was interested in knowing though if I can force the director recording to only be audio.... trying to work out a trouble free setup for a client to remote record podcasts, and at this stage only audio is required.

**Comment by steveseguin** [comment]
It's not super intutitive at the moment, apologies, but you can add &record={negative integer) to the URL to record audio-only as OPUS.   &record=0 I think does PCM (uncompressed)

https://vdo.ninja/?director=ROOM&showdirector&push=STREAMID&record=-100 

I probably should make a pop up for the director's record button, but you're the first person to even use the director record function from what I know.

**Comment by ConradHendricks** [comment]
ok cool. I'll give that a try. Ideally, I'd also love a big "RECORD" button somewhere in the Director that just starts local and remote record with already selected settings. 

Thank you so much for what you have created. This is just amazing. I am trying to get more people to use the service.... I'm in Melbourne, Australia and I also help 2 comedians with thier podcasts. One is here in Melbourne, the other in Sydney. I'm hoping to get the remote Sydney setup into OBS and doing anaudio Mixminus via ROdePodcaster here in Melbourne.... we are all in lockdown so none of us can get together properly to sort it all out.... can you believe I'm not allowed to go more that 5KM's from my house.... so I can't even get to my mate's house here in Melbourne to help him with the OBS/Rodecaster>Loopback setup to get it all going...... I know it'll be sweet when we do.

**Comment by steveseguin** [comment]
a big record button that records ALL the guests?  both local and remote?  not sure I understand the use case / purpose.

Thank you for the kind comment though; glad the software can be helpful in this odd time we live in.

**Comment by ConradHendricks** [comment]
IN an ideal world, that RECORD button could be have it's own menu where you can specify what will start recording when it's engaged. For example: a fictious podcast has the DIRECTOR as the host of the podcast and two guests. before the recording starts I can tell the RECORD button that I want to guests to  record locallly at a sepcified bit rate, and I want to record myself (DIRECTOR) at a specifeid bitrate, but audio only.    Then when I have all my guests ready to go, I just hit the big RECORD button and that button actions the other record buttons on the Director's page.... I hoe that makes sense.

**Comment by ConradHendricks** [comment]
I just tried to adding the &record=-100 to the director url and now I can't hear anything from a ninja session on the directors laptop. The headphones on this machine work fine, and I did a test record of the directors machine and I can hear audio on the webm file, but I can't seem to hear anything live.... I even created a whole new room, eneabled directors view, used a second computer to create a guest and I still can't hear anything in the directors room...
