### ISSUE TITLE
WS Service for own deployment lacks functionalities to feed the needs of webrtc.js library.

### ISSUE THREAD

**Issue by mbc-audiovisuales** [steveseguin/vdo.ninja#911]
Hi, provided WS project for private websockets service deployment is uncomplete. It in fact does its job as a websocket service. But it lacks all the obviously needed server side code to provide proper response contents back to the webrtc.js library.

It is confusing. It seems that code has not been made public, as of its lack into the Github repo. But you actively say we can have our own websocket service to avoid using your public one.

So?

Here is the screenshot of the message's sent & received via your public wss server. I've managed to deploy your proposed library as a ws server. It simply rebounds the message back to the ws client. 
![image](https://user-images.githubusercontent.com/71760897/140783623-c56a553a-babf-4b75-90ac-2148147e92f3.png)

Here using local deployed ws service:
![image](https://user-images.githubusercontent.com/71760897/140784361-78275d38-c81d-4a09-8f48-a863fb6301bf.png)

I have couple of working self developed and deployed WS services for different projeccts out there and seems to me that there is a lack of code for your proposed self deployed ws service.

Please decide:
- Or you deliver us the ws service code to deal with webrtc.js messages, in order to truly be able to deploy a private ws service by our own.
- Or please correct your documentation and state that using our own ws is not possible, as you are not providing essential server side code for an own deployed ws service.

Thanks!

**Comment by steveseguin** [comment]
Can you show me the settings in index.html that you used to configure the URL for the websocket?

You need to enable I think  `session.customWSS = true;`   else it won't work.

**Comment by jcalado** [comment]
I don't think opening an issue while ending it on an ultimatum is the best choice. No after 10 issues, let alone the first one.

Sorry I couldn't let this slide, but after all steve has given, for absolutely free, coming here and calling him a liar flat out is not cool by my book.

Just my two cents.

**Comment by mbc-audiovisuales** [comment]
Hi! Here is the configuration used. It is really simple

```

	var session = WebRTC.Media; 
	session.version = "19.4";
	session.streamID = session.generateStreamID();
	session.defaultPassword = "kkXmXwxtvlmB8c_general_production_site";
	session.salt = location.hostname;
	
	//session.wss = "wss://dev.streaming.websocket.com";
	session.wss = "wss://wss.vdo.ninja";
	session.customWSS = true;
	//session.pie = true;
```

Also tried combining it with session.pie uncommented. No difference.

Let me remark that, as seen at [https://github.com/steveseguin/websocket_server/blob/main/server.js](url), your proposed webserver simply rebounds received message. It is clear that webrtc.js library expects a WS API to talk to, and by using steveseguin's websocket sample server, webrtc.js finds a websocket service that has no API, instead finds a 'parrot-like' endpoint that returns a response containing the message it received from client.

I guess this alternative for handshaking lacks login into webrtc.js to really relay on own deployed websocket service for only handshaking. Seems it is trying to find out some kind of maybe API behaviour on self deployed WS service.

**Comment by steveseguin** [comment]
I wrote up a guide of configuring it and demoing it working for you. If things seem simple, keep in mind one of the philosophical goals of VDO.Ninja is to be serverless, so that's all intended.  Hopefully one day there will be no server code at all.

https://www.youtube.com/watch?v=xn7N5w7B2Ic

**Comment by mbc-audiovisuales** [comment]
That video is helpless. That video is showing backup.vdo.ninja production node in action. Is not using at all any local deployed instance. Please be real.

**Comment by edinsof** [comment]
Hello mbc
I am using self-hosted VDO ninja (html site - wss and turn server) and it works in its entirety, maybe you have something wrong configured

**Comment by mbc-audiovisuales** [comment]
Hi all, you all are right. I made a mistake configuring SSL cert. Sorry for my frustration. Seems everything works fine now.

Now it is working properly.

For me this thread should be closed as it was not an issue by yours but a mistake of mine.

Thanks!
