### ISSUE TITLE
Options are hidden when using Spanish and Basque language

### ISSUE THREAD

**Issue by Mixgyt** [steveseguin/vdo.ninja#913]
Some guest customization options are hidden in the control room when using the Spanish and Basque language, the bug also occurs when I want to customize the scene and group capture, but this time only with the Russian language

![image](https://user-images.githubusercontent.com/44759176/141707075-b076e96a-faf3-4aed-82bc-1e9902aae8cd.png)
![image](https://user-images.githubusercontent.com/44759176/141707873-4942b804-4ad3-4f76-957e-690ce2a7ad01.png)

I got this image using the Chrome developer options
![image](https://user-images.githubusercontent.com/44759176/141706937-2d5e1b28-edb1-43f0-81c2-bfcd724b4fc9.png)
![image](https://user-images.githubusercontent.com/44759176/141708070-1fd3b410-cbec-4764-9703-9c86f0be2ee1.png)

**Comment by steveseguin** [comment]
thank you

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/141729691-7106367f-fac1-42bd-ae7d-8fd899293c51.png)

Updated github and vdo.ninja/beta with some minor changes to make things less broken here.  Still ugly, but doesn't look as broken at least. 

https://vdo.ninja/beta & https://github.com/steveseguin/vdo.ninja/tree/v19.5-beta

**Comment by Mixgyt** [comment]
thanks for your work, vdo ninja is my favorite video calling platform.
