### ISSUE TITLE
WISH LIST: Settable delay for call in guest steam

### ISSUE THREAD

**Issue by nospam2k** [steveseguin/vdo.ninja#916]
I thought I would bounce this to you as it doesn't seem that OBS is addressing this issue. See https://obsproject.com/forum/threads/feature-request-stream-delay-censor-hotkey.73985/

The basic idea is a dump button for live streaming. Incoming a/v stream is delayed by X seconds. Should the incoming stream contain inappropriate audio or video, a dump button can be pressed to blank/mute X seconds of video/audio BEFORE it goes to OBS stream out.

My thinking is the idea of having two stream sources for each a/v with one a/v source delayed. The delayed source isn't heard or seen, but passed to OBS stream out. The non-delayed source is seen and heard by the director.

To sync, the director a/v would need to be at the same delay.

**Comment by steveseguin** [comment]
Hi nospam2k,

VDO.Ninja has a buffer delay command, which you can add to a scene or view link to delay the video's playback.

For example:
https://vdo.ninja/?scene&room=ROOMNAME&buffer=5000

This would delay the videos in the room by about 5-seconds (5000ms).  The director would still see the guests without any delay though, and can add/remove the offending guest from the scene without any delay.

The ability to mute and hide a guest, or remove from a scene, can be set as a hotkey for the director: MIDI API, HTTP API, or Bitfocus Companion app are examples of how the director can hot key a custom censor button, specific to their needs.  

Happy to discuss the fine details of what could be improved on.

**Note tho:**  The Buffer command does not work with OBS at the moment, as but it should work in an upcoming version of OBS with updated CEF.  It does work currently though with the Electron Capture app.

**Comment by nospam2k** [comment]
Thanks for the fast reply! I think 5 seconds may not be enough to respond, more like 10-15.

I hadn't expected such a fast response with a solution. I only just learned of Ninja. I'll play with it some and get a feel and come back and reopen when I have something to report.

**Comment by steveseguin** [comment]
In testing, I've been able to set the buffer as high as 10-seconds.  It doesn't look like 15-seconds is supported though.

just mentioning.  :)

**Comment by nospam2k** [comment]
10 Seconds might be ok. I'm not in a hurry for this but thanks for your help!
