### ISSUE TITLE
Translation for "You've been transferred to a different room"

### ISSUE THREAD

**Issue by micudaj** [steveseguin/vdo.ninja#919]
Hi,

first: Great tool you build here steve! Really like it!

A question: The message "You've been transferred to a different room" when a user has been transferred to a different room is inside the webrtc.js. Is there any way I can translate it?

Thanks and keep up the good work!
Mario

**Comment by steveseguin** [comment]
Thank you for reporting the issue.  It has been fixed on beta.

https://github.com/steveseguin/vdo.ninja/blob/ced13efd5a8978260e350fc07c5231156aace941/lib.js#L547

I've also updated the translation json files, in prep for the v20 release.  It includes these changes.

-steve

**Comment by micudaj** [comment]
Thank you for the fast response. I am thinking of utilizing it in a two day conference I am organizing from a technical point of view. If I do I will add german translations and contribute them.
