### ISSUE TITLE
The Docks's background color doesn't match chrome's.

### ISSUE THREAD

**Issue by iesvme** [steveseguin/vdo.ninja#925]
The Docks's background color doesn't match chrome's. The white color around doesn't look beautiful in OBS Docks.
![image](https://user-images.githubusercontent.com/16969250/149055314-5e58bdac-61d0-4aef-98cc-20c18c79e7af.png)
![image](https://user-images.githubusercontent.com/16969250/149055510-126da89d-9bc2-4957-acbf-016fbfb53583.png)

**Comment by steveseguin** [comment]
Thank you for pointing that out.

Until I get it fixed, you can add **&chroma=4C4C4C** to the dock URL to fix it.

`https://vdo.ninja/?director=ROOMID&chroma=4C4C4C`

**Comment by iesvme** [comment]
Thank you very much! By the way, hope to beautify the scrollbar in the next version!
