### ISSUE TITLE
How to customize the number of guest slot displayed; I want to display 3 slots instead of 4.

### ISSUE THREAD

**Issue by iesvme** [steveseguin/vdo.ninja#926]
![image](https://user-images.githubusercontent.com/16969250/149172670-57465ac4-ff02-495e-b50d-23f4e00c37f9.png)

**Comment by steveseguin** [comment]
I auto-hide those boxes now when they line-break.  No need to customize; should be automatic.
![image](https://user-images.githubusercontent.com/2575698/149329194-a7a7fb54-234e-4512-8c56-961ee9ce463b.png)

**Comment by iesvme** [comment]
Wonderful! It's the best way!

**Comment by iesvme** [comment]
Thank you so much for developing a such good software!

**Comment by steveseguin** [comment]
Thank you for the feedback.  I am not always aware of issues, so thank you

**Comment by iesvme** [comment]
Alright. It's my pleasure!
