### ISSUE TITLE
I am so sorry saying that: the white color of scrollbar is a little bit ugly. :(

### ISSUE THREAD

**Issue by iesvme** [steveseguin/vdo.ninja#927]
![image](https://user-images.githubusercontent.com/16969250/149303357-ab1b509c-36b6-4686-aa6b-99efd49a3032.png)

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/149323954-f1a75d3c-f112-42a3-9f33-94439041067a.png)
![image](https://user-images.githubusercontent.com/2575698/149324003-9cebd97e-0e9a-4b53-9af4-f066bf44cb2e.png)

Good?

**Comment by iesvme** [comment]
Yes! It's better than before!

These are beautiful, too.
![image](https://user-images.githubusercontent.com/16969250/149325911-d4459bd8-f427-42a7-84ab-6edd2c86369a.png)
