### ISSUE TITLE
Only audio

### ISSUE THREAD

**Issue by ImprezyLive** [steveseguin/vdo.ninja#931]
Hello,
i want send only audio feed, now i can hear from client to director but don't director to client if client have parameter &view without this parameter working.

What i need :
- director hear all connected
- all connected hear only director

I found solution - all connected must &view=STREAMID_DIRECTOR and Director must be a performer (is require?).

**Comment by steveseguin** [comment]
&view=streamID_Director is a good solution.  The director needs to be a performer if you want to be able to add them to scenes, but not if just talking between clients.
