### ISSUE TITLE
How to hide these buttons?

### ISSUE THREAD

**Issue by iesv** [steveseguin/vdo.ninja#932]
Hello, sir:
How to hide these buttons? Because of its default position, it often interferes with other button operations.
![image](https://user-images.githubusercontent.com/16969250/152740322-35d19ab3-89d8-4e3e-9998-2c07dc0c2882.png)

**Comment by steveseguin** [comment]
- You can drag it out of the way.
- You can add &cleanoutput 
- &autohide will have the controls fade out after 5 seconds (and show again when you move the mouse)

if you're using a version of vdo.ninja from the last couple of weeks, the director has more vertical room, so it shouldn't be interfering if  you scroll down a bit.
![image](https://user-images.githubusercontent.com/2575698/153745154-c2f04255-2dcd-4716-92d8-84f5b47a60a2.png)

**Comment by iesvme** [comment]
Thank you for your patient answer. But these three methods are not good
enough for me. It would be nice if it could be hidden or shown on the side.

Steve Seguin ***@***.***> 于2022年2月13日周日 16:28写道：

**Comment by rse** [comment]
If none of Steve's mentioned approaches are fine for you, just take the hammer and inject a custom CSS via the &css option and in this style sheet just disable the buttons you really want to completely get rid of.
