### ISSUE TITLE
Feature Request: Set No-Video background/colour

### ISSUE THREAD

**Issue by freadZdead** [steveseguin/vdo.ninja#957]
Hi @steveseguin ,

Again, not one too high on the priority list, but it would be amazing to have something like &bg=#000000 or even &bgimg=url to set the default background to a colour or (even better) an image when no video is present, to something different than the dark blue that seems to be the current setting - again, no hurry on this, but would be nice to have :).

Cheers,

Freddy

**Comment by steveseguin** [comment]
&chroma= lets you set the background color.  Transparencies will work within OBS, but may not work with iframes, etc.

&chroma=F005 for example should give you a pink color or a translucent red, depending on whether the page supports transparencies.

I've added support for background images to the vdo.ninja/alpha/mixer , where you can select an image as a background for specific video elements in a layout, but it needs a generic option and more testing. Currently it works on alpha, but you need to feed custom layouts via the URL or API with the Image link you want included in those layout requests.  [WIP]

There's also [&style=0 and &style=6 ](https://vdo.ninja/?view=xxxxxx&style=6) , which sets a little avatar man as the default background image, if there's no video at least.  You can customize this avatar to be a different image with &bgimage, passing a base64 data img/svg object , or a URL (url encoded).  It's on alpha and only impacts the local viewer, asits just a CSS tweak really.

ie: https://vdo.ninja/alpha/?view=aSmexM6&style=0&bgimage=https%3A%2F%2Fvdo.ninja%2Fmedia%2Fold_icon.png

There's also &avatar, https://docs.vdo.ninja/advanced-settings/upcoming-parameters/and-avatar, which lets a custom image to be selected by a user to be their own default background image.  This applies not just to the local user, but it actually becomes the avatar for that user when they mute their video. 

If more options or tweaks needed, let me know.

**Comment by freadZdead** [comment]
Hi @steveseguin ,

&chroma works a treat, thank you!

Neither alpha &style0 or &style6 seem to be doing anything for me, although I made sure the machine can access the example icon via URL itself - strange. Maybe it is me also expecting it to behave differently - I would like to see it when I have a specific view=PUSH_ID on, and the user is still offline, if that makes sense... should it do that?

as we need to KISS for the user, and really only need to control it on our end, I'll probably pass on &avatar.

Cheers,

Freddy

**Comment by freadZdead** [comment]
Hey @steveseguin ,

Thank you for the explanation, makes sense; unfortunately, because I am not using OBS but an ATEM Switcher, I would need to use a Chroma or Luma Key in order to put anything behind a source - but that is a bit risky in terms of unwanted keying during the actual working of the connection... as the goal would be that it would be an avatar/logo/source disconnect only visible if/when the source literally disconnects/disappears due to an issue on the remote end.

So ultimately, some sort of feature to have a background image behind a disconnected source when using &view would still be usable in vdo.ninja - if at all conceivable/doable.

Cheers,

Freddy

**Comment by steveseguin** [comment]
Thank you for the clarification.  I'll see what I can do. Do you only ever have a single video per window? or are you using a group scene?

It's far easier for me to make a global background image, that shows when there are simply no videos active.

**Comment by freadZdead** [comment]
No worries - and correct, in my scenario, it is only ever one remote participant being viewed, so a global background (per window) would totally work - but of course no stress if other issues have priority :).

Cheers,

Freddy

**Comment by steveseguin** [comment]
added **&background** / &appbg , which accepts a URL-encoded image URL to make as the app's default background.  For example,
 
 ` https://vdo.ninja/alpha/?appbg=./media/logo_cropped.png `
 
 The image will scale in size to cover the VDO.Ninja app's background.  &chroma can still be used to set the background color, if using transparencies.    There already exists &bgimg, which will set the default background image for videos; this however will set a background image for the entire page.
 
 
![image](https://user-images.githubusercontent.com/2575698/176809582-8ad8bb2d-bb2d-4d34-87a0-83a688b95301.png)

**Comment by freadZdead** [comment]
Thanks @steveseguin ,

We have it in production with elegant loops as animated gifs and are absolutely loving it!

Cheers,
Freddy
