### ISSUE TITLE
How to enable supported option "WhiteBalanceMode" on phone's camera?

### ISSUE THREAD

**Issue by floyd168** [steveseguin/vdo.ninja#969]
Checked https://vdo.ninja/supports On Android phone , it's shown WhiteBlanceMode support. 
How to add parameter to enable this option to manual white balance ?  Could it work on iPhone?  
Thanks!!

**Comment by steveseguin** [comment]
It won't work on iPhone at the moment, but will work with Android and some webcams.

If you join a group room, the director has control of the white balance I think.

If you join with just a plain push-link though, you'll have the options via settings -> video

There is an option for "white balance ->manual/continuous

There's also a "colorTemperature" slider.    The white balance will automatically switch to to manual if you change the color-balance.  Trying to force white balance to manual while the temperture is 0 (or something incompatible), may fail to have it switch to manual.

I tested on my pixel 4a here just now and it works.  I do need to do more work here, to make the UI/UX a bit easier; feedback welcomed.

![image](https://user-images.githubusercontent.com/2575698/176411823-8f56b7e6-90c7-4214-a7a3-a3f2534306b3.png)

As for iPhones, Apple doesn't support much with Safari, so I'll likely need to add this to the native app at some point instead.  That will take time

**Comment by floyd168** [comment]
Got it! Thanks for your speedy reply!
